config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: "portfolios#show", as: "portfolio_show"

  get 'about', to: "pages#about"

  resources :blogs do
    member do
      get :toggle_status, to: "blogs#toggle_status"
    end
  end

  get 'pages/index'
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :topic
  validates :title, presence: :true
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "https://placehold.it/#{height}x#{width}"
  end

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
has_many :technologies
accepts_nested_attributes_for :technologies,
              reject_if: lambda {|attrs| attrs['name'].blank?}

include Placeholder

validates_presence_of :title, :body, :main_image, :thumb_image

scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby on Rails')}

after_initialize :set_defaults


def set_defaults
  self.main_image ||= Placeholder.image_generator(height: "600", width: "400")
  self.thumb_image ||= Placeholder.image_generator(height: "300", width: "150")
  # Two pipe operator is if nil then set image

end


end

app/models/skill.rb
class Skill < ApplicationRecord
include Placeholder

after_initialize :set_defaults

def set_defaults
  self.badge ||= Placeholder.image_generator(height: "100", width: "100")
end



end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include SetDefaultAttributes

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
    layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    @page_header = "Blogs"
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  def toggle_status
    @blog.draft? ? @blog.published! : @blog.draft!

    redirect_to blogs_path, notice: "Blog status updated!"
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    OpenStruct.new(name: "Tim Jones",
                  first_name: "Tim",
                   last_name: "Jones",
                    email: "tim@jones.me"
                    )
  end

end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
      before_action :configure_permitted_parameters, if: :devise_controller?
  end

    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/concerns/set_default_attributes.rb
module SetDefaultAttributes
  extend ActiveSupport::Concern

  included do
    before_action :set_default_attributes
  end


    def set_default_attributes
      @page_header = "Dev Camp Blog"
      @seo_keywords = "Blogs Portfolios"
    end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

included do
  before_action :set_source
end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def index
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout "portfolio"

  def index
    @page_header = "Portfolios"
    @seo_keywords = "Portfolio stuff and other key words"
    @portfolio_items = Portfolio.all
  end

  def show
  end

  def edit
    3.times { @portfolio.technologies.build}

    end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        # QUESTION: why does .update method work here .. where is it written? ACTIVE RECORD?
        format.html { redirect_to portfolio_show_path(@portfolio), notice: 'portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @portfolio = Portfolio.new
    3.times { @portfolio.technologies.build}
  end

  def destroy
    @portfolio.technologies.all.each {|t| t.destroy}
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create

    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

end

private

def set_portfolio
  @portfolio = Portfolio.find_by(id: params[:id])
end

def portfolio_params
  params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sample_helper
    "<p>My helper</p>".html_safe
    content_tag(:div, "My Content", class: "my-class")
  end

  def login_helper
    if current_user.is_a?(User)
     link_to "Logout", destroy_user_session_path, method: :delete
    else
     (link_to "Register", new_user_registration_path ) +
     "<br>".html_safe +
     (link_to "Login", new_user_session_path)
    end
  end

  def session_helper
    if session[:source]
      content_tag(:p,
        "Thanks for visiting me from #{session[:source]}"
        )

    end

  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
     <tr>
        <td><%= blog.title %></td>
        <td>published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @blogs %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DissectingRubyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <% if current_user.is_a?(User) %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to "Register", new_user_registration_path %>
    <%= link_to "Login", new_user_session_path %>
    <% end %>

    <%= yield %>

    <% if session[:source] %>
      <p>Thanks for visiting me from <%= session[:source] %></p>
    <% end %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_header %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content="<%= @seo_keywords %>" />


    <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= login_helper %>

    <%= yield %>

      <%= render "shared/navbar.html.erb", location: "bottom" %>
    <%= session_helper %>

  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_header %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content="<%= @seo_keywords %>" />


    <%= stylesheet_link_tag 'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render "shared/navbar.html.erb", location: "top" %>


       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= login_helper %>


    <%= yield %>

    <%= session_helper %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi <%= current_user.first_name if current_user %></h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog Posts</h1>
<%= @blogs.inspect %>

<h1>Skills</h1>

<%= @skills.inspect %>

<%= sample_helper %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/portfolios/_form.html.erb
<div>
  <%= form_for(@portfolio) do |f| %>

 <%= f.label :title, placeholder: "Title of portfolio" %>
 <%= f.text_field :title %>

<%= f.label :subtitle, placeholder: "Subtitle" %>
 <%= f.text_field :subtitle %>

  <%= f.label :body, placeholder: "body of portfolio" %>
 <%= f.text_field :body %>

<ul>
  <%= f.fields_for :technologies do |technology_form| %>
    <%= technology_form.label :name %>
    <%= technology_form.text_field :name %>
  <% end %>
</ul>


  <%= f.submit %>
<% end %>

</div>

app/views/portfolios/_portfolio_item.html.erb
  <p><%= portfolio_item.title %></p>

  <p><%= portfolio_item.subtitle %></p>

  <p><%= portfolio_item.body %></p>
  <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>


<%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
  <%= link_to 'Edit', edit_portfolio_path(portfolio_item) %>
 <%= link_to 'Destroy', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %>




  <br>
  <hr>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio</h1>

  <%= render "form", portfolio: @portfolio %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "New Portfolio", new_portfolio_path %>

<%= render partial: "portfolio_item", collection: @portfolio_items  %>

app/views/portfolios/new.html.erb
<h1>New Portfolio Item</h1>

<%= render "form", portfolio: @portfolio %>

app/views/portfolios/show.html.erb
<h1>Show portfolio here</h1>

<%= image_tag @portfolio.main_image %>

<h1><%= @portfolio.title %></h1>

<h2><em><%= @portfolio.subtitle %></em></h2>

<p><%= @portfolio.body %></p>

<h2>Tech used</h2>

<% @portfolio.technologies.each do |t| %>
  <p>
    <%= t.name %>
  </p>
<% end %>

app/views/shared/_navbar.html.erb
<div class="<%= location %>">
      <%= link_to "Home", root_path %>
      <%= link_to "About", about_path  %>
      <%= link_to "Blogs", blogs_path %>
      <%= link_to "Portfolios", portfolios_path %>

</div>